CREATE TABLE PERSON
(
	UNIQUE_ID VARCHAR(200) PRIMARY KEY,
	NAME VARCHAR(200) NOT NULL
);

CREATE TABLE PERSON_IDENTIFICATION
(
	UNIQUE_ID VARCHAR(200) NOT NULL,
	ID VARCHAR(200) NOT NULL,
	ID_TYPE ENUM('AADHAAR', 'PAN', 'VOTER', 'DRIVING') NOT NULL,
	NAME VARCHAR(200) NOT NULL,
	DOB DATE NOT NULL,
	PRIMARY KEY (UNIQUE_ID, ID, ID_TYPE)
);

CREATE TABLE PERSON_VALIDATION
(
	UNIQUE_ID VARCHAR(200) NOT NULL,
	ID VARCHAR(200) NOT NULL,
	ID_TYPE ENUM('AADHAAR', 'PAN', 'VOTER', 'DRIVING') NOT NULL,
	NAME_MATCH BOOLEAN NOT NULL,
	DOB_MATCH BOOLEAN NOT NULL,
	PRIMARY KEY (UNIQUE_ID, ID, ID_TYPE)
);